apiVersion: apps/v1
kind: Deployment
metadata:
  name: "resti"
  labels:
    app: "resti"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "resti"
  template:
    metadata:
      labels:
        app: "resti"
    spec:
      containers:
        - name: "flask-app"
          image: sk123456789/resty:v4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
          - name: kube-config
            mountPath: "/opt"
          env:
          - name: KUBECONFIG
            value: "/opt/kube-config"
      volumes:
      - name: kube-config
        secret:
          secretName: kube-config
          items:
          - key: config_out
            path: kube-config
---
apiVersion: v1
kind: Service
metadata:
  name: "resti-srv"
  labels:
    srv: "resti"
spec:
  type: NodePort
  selector:
    app: "resti"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
