---
- name: Install and configure web server
  hosts: all
  become: yes
  tasks:
    - name: Install web server
      apt:
        name: apache2
        state: present
    - name: Configure web server
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
    - name: Ensure web server is running
      service:
        name: apache2
        state: started
        enabled: yes

